### ISSUE TITLE
System.ArgumentException: The directory name  is invalid. (Parameter 'path')

### ISSUE THREAD

**Issue by j-masci** [Smibu/elmanager#138]
Something to do with my environment maybe? Any ideas?

This occurs when trying to open the replay manager or level manager, but not SLE.

```
Exception Text 

System.ArgumentException: The directory name  is invalid. (Parameter 'path')
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at Elmanager.Forms.Manager`1..ctor(IManagerGui m)
   at Elmanager.Forms.ReplayManager..ctor()
   at Elmanager.ComponentManager.LaunchReplayManager()
   at Elmanager.Forms.MainForm.OpenReplayManager(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies

System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.47201
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Private.CoreLib.dll
----------------------------------------
Elmanager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.35.1524
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Elmanager.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.Security.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Collections.Concurrent.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.46503
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Windows.Forms.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.IO.Compression.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Collections.NonGeneric.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.IO.FileSystem.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Linq.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Diagnostics.Process.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.ComponentModel.Primitives.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Resources.Extensions.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Drawing.Primitives.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/mscorlib.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.46503
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Drawing.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Collections.Specialized.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.Requests.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Newtonsoft.Json.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Private.Uri.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.Primitives.dll
----------------------------------------
System.Security.Principal
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Principal.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.Http.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.NetworkInformation.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Threading.Thread.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.InteropServices.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.46503
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Accessibility.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.ComponentModel.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Net.NameResolution.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 4.1.3.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Claims.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Threading.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 4.1.3.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Collections.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.Numerics.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Data.Common.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Private.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.700.20.47201
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Private.CoreLib.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/ObjectListView.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.20.47203
    CodeBase: file:///C:/Users/Joel/AppData/Local/Temp/.net/Elmanager/hsnltg15.4vj/System.Reflection.Metadata.dll
----------------------------------------
```

**Comment by j-masci** [comment]
Sorry for the retarded formatting.

**Comment by j-masci** [comment]
Ok I just had to go into Configuration and add the directories. Sorry...

**Comment by Smibu** [comment]
Thanks for reporting! Even without configuration, it should display some sensible error message instead of crashing like that. I'll leave this open until this is fixed.

**Comment by Smibu** [comment]
This should be fixed in the Feb 2021 version. I should update the changelog...
