### ISSUE TITLE
Crash when Elma folder is moved

### ISSUE THREAD

**Issue by Smibu** [Smibu/elmanager#73]
In GitLab by @Smibu on Sep 30, 2016, 22:44

Reported by sunl:

> Was making level at C:\Users\xxx\Documents\Temp\a\EOL\lev\quizrl3b.lev, SLE folder is in EOL folder. Closed editor. Then moved whole EOL folder to somewhere else. Get this error when clicking on the "SLE" button at the opening window

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\xxx\Documents\Temp\a\EOL\lev\quizrl3b.lev'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
at Elmanager.Level.LoadFromPath(String levelPath)
at Elmanager.Forms.LevelEditor.TryLoadLevel(String levPath)
at Elmanager.Forms.LevelEditor..ctor()
at Elmanager.Forms.MainForm.OpenLevelEditor(Object sender, EventArgs e)
```

**Comment by Smibu** [comment]
In GitLab by @Smibu on Oct 12, 2016, 21:30

Status changed to closed by commit 4e4e871dd0dc64621df9b79d62c9a0b3315217ab
